
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const CAPTAIN: EnemyConfig = {
  archetype: 'captain',
  boss: bossLifecycle('THE CAPTAIN OF THE GUARD'),
  maxHp: 840,
  maxPoise: 240,
  poiseRegenPerSec: 18,
  moveSpeed: 3.2,
  acceleration: 20,
  turnRate: 5.5,
  radius: 0.62,
  knockbackScale: 0.25,
  preferredRange: 2.15,
  attackRange: 2.75,
  defence: {
    arcDeg: 240,
    chipFraction: 0.12,
    provokedCooldownMs: 340,
    unearned: {
      parryEveryNth: 3,
      parryStaminaCost: 25,
      counterCooldownMs: 0,
      parryHitstopMs: 160,
    },
  },
  attacks: [
    {
      id: 'captain_direct',
      tell: 'chop',
      telegraphMs: 620,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 420,
      range: 2.35,
      arcDeg: 92,
      damage: 18,
      lungeDistance: 0.5,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'captain_feint',
      tell: 'chop',
      telegraphMs: 1180,
      telegraphJitterMs: 0,
      feint: {
        atMs: 360,
        resetMs: 180,
      },
      activeMs: 95,
      recoveryMs: 360,
      range: 2.35,
      arcDeg: 92,
      damage: 20,
      lungeDistance: 0.5,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'captain_pressure',
      tell: 'jab',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 220,
      range: 1.95,
      arcDeg: 54,
      damage: 12,
      lungeDistance: 0.35,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'captain_release',
      tell: 'sweep',
      telegraphMs: 760,
      telegraphJitterMs: 0,
      activeMs: 110,
      recoveryMs: 760,
      range: 3.05,
      arcDeg: 144,
      damage: 24,
      lungeDistance: 0.7,
      parryable: true,
      kind: 'melee',
    },
  ],
  attackPattern: [0, 2, 3, 0, 2],
  attackPatternPhaseTwo: [0, 1, 2, 2, 2, 3],
  summon: {
    archetype: 'guard',
    fromPhase: 2,
    everyPhrases: 1,
    maxAlive: 2,
    offsets: [
      { x: -2.4, y: 1.6 },
      { x: -2.4, y: -1.6 },
    ],
  },
  attackCooldownMs: 340,
  attackCooldownJitterMs: 0,
  staggerMs: 1350,
};
