
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const ELITE_GUARD: EnemyConfig = {
  archetype: 'elite_guard',
  boss: bossLifecycle('WALL STUDY'),
  maxHp: 740,
  maxPoise: 260,
  poiseRegenPerSec: 11,
  moveSpeed: 2.8,
  acceleration: 18,
  turnRate: 4.5,
  radius: 0.62,
  preferredRange: 2.2,
  attackRange: 3,
  defence: {
    arcDeg: 150,
    chipFraction: 0.25,
    provokedCooldownMs: 220,
  },
  attacks: [
    {
      id: 'elite_guard_counter',
      telegraphMs: 520,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 380,
      range: 2.3,
      arcDeg: 88,
      damage: 18,
      lungeDistance: 0.5,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'elite_guard_sweep',
      telegraphMs: 820,
      telegraphJitterMs: 0,
      activeMs: 120,
      recoveryMs: 520,
      range: 3,
      arcDeg: 165,
      damage: 26,
      lungeDistance: 0.4,
      parryable: false,
      kind: 'melee',
    },
    {
      id: 'elite_guard_thrust',
      telegraphMs: 620,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 900,
      range: 3.6,
      arcDeg: 40,
      damage: 22,
      lungeDistance: 1.9,
      parryable: true,
      kind: 'melee',
    },
  ],
  attackPattern: [0, 1, 0, 2],
  attackCooldownMs: 1600,
  attackCooldownJitterMs: 0,
  staggerMs: 1600,
};
