
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const FIRST_BLADE: EnemyConfig = {
  archetype: 'first_blade',
  boss: bossLifecycle('THE FIRST BLADE'),
  maxHp: 780,
  maxPoise: 420,
  poiseRegenPerSec: 16,
  moveSpeed: 7.2,
  acceleration: 45,
  turnRate: 8,
  radius: 0.58,
  preferredRange: 2.8,
  attackRange: 3.2,
  attacks: [
    {
      id: 'first_blade_sequence_open',
      telegraphMs: 520,
      telegraphJitterMs: 0,
      activeMs: 85,
      recoveryMs: 260,
      range: 3.1,
      arcDeg: 62,
      damage: 20,
      lungeDistance: 1.4,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'first_blade_sequence_turn',
      telegraphMs: 430,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 240,
      range: 3.0,
      arcDeg: 58,
      damage: 22,
      lungeDistance: 1.2,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'first_blade_sequence_close',
      telegraphMs: 360,
      telegraphJitterMs: 0,
      activeMs: 95,
      recoveryMs: 820,
      range: 3.2,
      arcDeg: 68,
      damage: 26,
      lungeDistance: 1.6,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'first_blade_glide_open',
      telegraphMs: 300,
      telegraphJitterMs: 0,
      activeMs: 1300,
      recoveryMs: 150,
      range: 1.15,
      arcDeg: 180,
      damage: 16,
      lungeDistance: 0,
      parryable: true,
      kind: 'melee',
      traversesArena: true,
    },
    {
      id: 'first_blade_glide_chain',
      telegraphMs: 220,
      telegraphJitterMs: 0,
      activeMs: 1300,
      recoveryMs: 130,
      range: 1.15,
      arcDeg: 180,
      damage: 17,
      lungeDistance: 0,
      parryable: true,
      kind: 'melee',
      traversesArena: true,
    },
    {
      id: 'first_blade_glide_close',
      telegraphMs: 260,
      telegraphJitterMs: 0,
      activeMs: 1300,
      recoveryMs: 980,
      range: 1.25,
      arcDeg: 180,
      damage: 24,
      lungeDistance: 0,
      parryable: true,
      kind: 'melee',
      traversesArena: true,
    },
    {
      id: 'first_blade_sequence_low',
      telegraphMs: 600,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 300,
      range: 2.6,
      arcDeg: 150,
      damage: 20,
      lungeDistance: 0.9,
      parryable: true,
      kind: 'melee',
    },
  ],
  attackCooldownMs: 1250,
  attackCooldownJitterMs: 0,
  staggerMs: 1350,
  sequence: {
    attackIndices: [0, 1, 2],
    altAttackIndices: [6, 1, 2],
    repositionMs: 650,
    orbitRadius: 2.7,
    angleStepRad: (Math.PI * 2) / 3,
    idleOrbitScale: 0.72,
    phaseTwo: {
      attackIndices: [3, 4, 4, 4, 5],
      repositionMs: 95,
      orbitRadius: 3.1,
      angleStepRad: (Math.PI * 2) / 5,
      edgeVisits: 2,
      edgeInset: 0.7,
      edgeMoveTimeoutMs: 1300,
      moveSpeedScale: 1.45,
      glideSpeed: 24,
    },
  },
};
