
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const GLASS_REGENT: EnemyConfig = {
  archetype: 'glass_regent',
  boss: bossLifecycle('THE GLASS REGENT'),
  maxHp: 620,
  maxPoise: 420,
  poiseRegenPerSec: 14,
  moveSpeed: 3.0,
  acceleration: 26,
  turnRate: 6.0,
  radius: 0.58,
  knockbackScale: 0,
  preferredRange: 2.6,
  attackRange: 3.4,
  volley: {
    integrity: 6,
    maxLive: [1, 1],
    speedScalePerReturn: 1.07,
    shatterDamage: 34,
    shatterStaggerMs: 7000,
    shardLifeMs: 6000,
    shockwave: {
      cornerRadius: 5.4,
      damage: 18,
      openingShoveMs: 620,
    },
    wardRadius: 2.0,
    wardPushDistance: 2.2,
    wardPushMs: 280,
    reserveCooldownMs: 260,
    homingRateRad: 1.8,
    wardPushCooldownMs: 700,
  },
  attacks: [
    {
      id: 'glass_regent_slam',
      telegraphMs: 1900,
      telegraphJitterMs: 0,
      activeMs: 120,
      recoveryMs: 380,
      range: 0,
      arcDeg: 360,
      damage: 26,
      lungeDistance: 0,
      parryable: false,
      kind: 'shockwave',
      tell: 'chop',
    },
    {
      id: 'glass_regent_serve',
      telegraphMs: 760,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 420,
      range: 0,
      arcDeg: 0,
      damage: 16,
      lungeDistance: 0,
      parryable: true,
      kind: 'volley',
      projectileSpeed: 11,
      tell: 'thrust',
    },
    {
      id: 'glass_regent_quick_serve',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 240,
      range: 0,
      arcDeg: 0,
      damage: 16,
      lungeDistance: 0,
      parryable: true,
      kind: 'volley',
      projectileSpeed: 13,
      tell: 'jab',
    },
    {
      id: 'glass_regent_cleave',
      telegraphMs: 640,
      telegraphJitterMs: 0,
      activeMs: 120,
      recoveryMs: 760,
      range: 2.8,
      arcDeg: 200,
      damage: 30,
      lungeDistance: 0.9,
      parryable: false,
      kind: 'melee',
      tell: 'chop',
    },
  ],
  attackPattern: [1, 1, 1],
  attackPatternPhaseTwo: [2, 2, 2],
  attackCooldownMs: 800,
  attackCooldownJitterMs: 0,
  staggerMs: 1400,
};
