
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const PIKE_BOSS: EnemyConfig = {
  archetype: 'pike_boss',
  boss: bossLifecycle('REACH STUDY'),
  maxHp: 700,
  maxPoise: 420,
  poiseRegenPerSec: 16,
  moveSpeed: 2.9,
  acceleration: 16,
  turnRate: 2.4,
  radius: 0.58,
  preferredRange: 3.6,
  attackRange: 4.0,
  attacks: [
    {
      id: 'pike_boss_thrust',
      telegraphMs: 640,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 660,
      range: 3.9,
      arcDeg: 32,
      damage: 20,
      lungeDistance: 1.6,
      parryable: true,
      kind: 'melee',
      tell: 'thrust',
    },
    {
      id: 'pike_boss_sweep',
      telegraphMs: 780,
      telegraphJitterMs: 0,
      activeMs: 120,
      recoveryMs: 620,
      range: 3.2,
      arcDeg: 150,
      damage: 24,
      lungeDistance: 0.5,
      parryable: false,
      kind: 'melee',
      tell: 'sweep',
    },
    {
      id: 'pike_boss_drive',
      telegraphMs: 820,
      telegraphJitterMs: 0,
      activeMs: 110,
      recoveryMs: 780,
      range: 3.4,
      arcDeg: 44,
      damage: 26,
      lungeDistance: 3.4,
      parryable: true,
      kind: 'melee',
      tell: 'chop',
    },
  ],
  attackPattern: [0, 0, 1],
  attackPatternPhaseTwo: [2, 0, 1, 0],
  attackCooldownMs: 1100,
  attackCooldownJitterMs: 0,
  staggerMs: 1350,
};
