
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const QUEEN: EnemyConfig = {
  archetype: 'queen',
  boss: {
    ...bossLifecycle('THE QUEEN'),
    phaseThreeHpFraction: 0.25,
  },
  maxHp: 880,
  maxPoise: 460,
  poiseRegenPerSec: 18,
  moveSpeed: 4.6,
  acceleration: 40,
  turnRate: 8.5,
  radius: 0.56,
  knockbackScale: 1.15,
  preferredRange: 3.0,
  attackRange: 3.5,
  attacks: [
    {
      id: 'queen_decree_thrust',
      telegraphMs: 460,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 300,
      range: 3.3,
      arcDeg: 46,
      damage: 18,
      lungeDistance: 1.5,
      parryable: true,
      kind: 'melee',
      tell: 'thrust',
    },
    {
      id: 'queen_decree_chop',
      telegraphMs: 400,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 280,
      range: 3.0,
      arcDeg: 64,
      damage: 22,
      lungeDistance: 1.1,
      parryable: true,
      kind: 'melee',
      tell: 'chop',
    },
    {
      id: 'queen_decree_close',
      telegraphMs: 520,
      telegraphJitterMs: 0,
      activeMs: 100,
      recoveryMs: 780,
      range: 2.9,
      arcDeg: 120,
      damage: 26,
      lungeDistance: 1.3,
      parryable: true,
      kind: 'melee',
      tell: 'sweep',
    },
    {
      id: 'queen_decree_feint',
      telegraphMs: 620,
      telegraphJitterMs: 0,
      feint: { atMs: 300, resetMs: 200 },
      activeMs: 90,
      recoveryMs: 300,
      range: 3.3,
      arcDeg: 46,
      damage: 18,
      lungeDistance: 1.5,
      parryable: true,
      kind: 'melee',
      tell: 'thrust',
    },

    {
      id: 'queen_twin_open',
      telegraphMs: 320,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 240,
      range: 3.0,
      arcDeg: 70,
      damage: 18,
      lungeDistance: 1.0,
      parryable: true,
      kind: 'melee',
      tell: 'chop',
    },
    {
      id: 'queen_twin_cross',
      telegraphMs: 280,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 220,
      range: 3.4,
      arcDeg: 52,
      damage: 20,
      lungeDistance: 2.2,
      parryable: true,
      kind: 'melee',
      tell: 'thrust',
    },
    {
      id: 'queen_crescent_low',
      telegraphMs: 560,
      telegraphJitterMs: 0,
      activeMs: 110,
      recoveryMs: 420,
      range: 2.7,
      arcDeg: 200,
      damage: 30,
      lungeDistance: 0.8,
      parryable: false,
      kind: 'melee',
      tell: 'sweep',
    },
    {
      id: 'queen_twin_close',
      telegraphMs: 300,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 700,
      range: 3.1,
      arcDeg: 74,
      damage: 22,
      lungeDistance: 1.2,
      parryable: true,
      kind: 'melee',
      tell: 'chop',
    },

    {
      id: 'queen_last_decree_rain',
      telegraphMs: 700,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 200,
      range: 0,
      arcDeg: 360,
      damage: 20,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 1100,
        impactRadius: 0.8,
        offsets: [
          { x: 0, y: 2.3 },
          { x: 1.99, y: 1.15 },
          { x: 1.99, y: -1.15 },
          { x: 0, y: -2.3 },
          { x: -1.99, y: -1.15 },
          { x: -1.99, y: 1.15 },
        ],
      },
    },
    {
      id: 'queen_glaive_sweep',
      telegraphMs: 520,
      telegraphJitterMs: 0,
      activeMs: 120,
      recoveryMs: 380,
      range: 3.0,
      arcDeg: 230,
      damage: 32,
      lungeDistance: 1.6,
      parryable: false,
      kind: 'melee',
      tell: 'sweep',
    },
    {
      id: 'queen_glaive_riposte',
      telegraphMs: 260,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 900,
      range: 3.5,
      arcDeg: 48,
      damage: 24,
      lungeDistance: 2.4,
      parryable: true,
      kind: 'melee',
      tell: 'thrust',
    },
    {
      id: 'queen_last_decree_rain_tight',
      telegraphMs: 640,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 200,
      range: 0,
      arcDeg: 360,
      damage: 20,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 850,
        impactRadius: 0.8,
        offsets: [
          { x: 0, y: 1.7 },
          { x: 1.47, y: 0.85 },
          { x: 1.47, y: -0.85 },
          { x: 0, y: -1.7 },
          { x: -1.47, y: -0.85 },
          { x: -1.47, y: 0.85 },
        ],
      },
    },
  ],
  attackCooldownMs: 900,
  attackCooldownJitterMs: 0,
  staggerMs: 1250,
  sequence: {
    attackIndices: [0, 1, 2],
    altAttackIndices: [3, 1, 2],
    repositionMs: 560,
    orbitRadius: 3.0,
    angleStepRad: (Math.PI * 2) / 3,
    idleOrbitScale: 0.85,
    movements: [
      {
        attackIndices: [4, 5, 6, 7],
        altAttackIndices: [4, 6, 5, 7],
        repositionMs: 380,
        orbitRadius: 2.6,
        angleStepRad: (Math.PI * 2) / 5,
        moveSpeedScale: 1.25,
      },
      {
        attackIndices: [8, 9, 10],
        altAttackIndices: [11, 9, 10],
        repositionMs: 300,
        orbitRadius: 3.2,
        angleStepRad: (Math.PI * 5) / 6,
        moveSpeedScale: 1.45,
      },
    ],
  },
};
