
import type { EnemyConfig } from '../../sim/types';
import { bossLifecycle } from './boss-lifecycle';

export const RAIN_BOSS: EnemyConfig = {
  archetype: 'rain_boss',
  boss: bossLifecycle('PERIPHERAL STUDY'),
  maxHp: 640,
  maxPoise: 240,
  poiseRegenPerSec: 18,
  moveSpeed: 2.6,
  acceleration: 18,
  turnRate: 5,
  radius: 0.62,
  preferredRange: 4,
  attackRange: 6,
  attacks: [
    {
      id: 'rain_cross',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 80,
      range: 0,
      arcDeg: 360,
      damage: 18,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 1250,
        impactRadius: 0.78,
        offsets: [
          { x: 0, y: 0 },
          { x: -2.4, y: 0 },
          { x: 2.4, y: 0 },
          { x: 0, y: -2.4 },
          { x: 0, y: 2.4 },
        ],
      },
    },
    {
      id: 'rain_focus',
      telegraphMs: 520,
      telegraphJitterMs: 0,
      activeMs: 90,
      recoveryMs: 260,
      range: 4.8,
      arcDeg: 52,
      damage: 20,
      lungeDistance: 0.2,
      parryable: true,
      kind: 'melee',
    },
    {
      id: 'rain_diagonal',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 80,
      range: 0,
      arcDeg: 360,
      damage: 18,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 1250,
        impactRadius: 0.78,
        offsets: [
          { x: 0, y: 0 },
          { x: -1.75, y: -1.75 },
          { x: 1.75, y: -1.75 },
          { x: -1.75, y: 1.75 },
          { x: 1.75, y: 1.75 },
        ],
      },
    },
    {
      id: 'rain_ring',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 80,
      range: 0,
      arcDeg: 360,
      damage: 18,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 1250,
        impactRadius: 0.78,
        offsets: [
          { x: 0, y: 2.15 },
          { x: 2.04, y: 0.66 },
          { x: 1.26, y: -1.74 },
          { x: -1.26, y: -1.74 },
          { x: -2.04, y: 0.66 },
        ],
      },
    },
    {
      id: 'rain_cross_tight',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 80,
      range: 0,
      arcDeg: 360,
      damage: 18,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 950,
        impactRadius: 0.78,
        offsets: [
          { x: 0, y: 0 },
          { x: -2.4, y: 0 },
          { x: 2.4, y: 0 },
          { x: 0, y: -2.4 },
          { x: 0, y: 2.4 },
        ],
      },
    },
    {
      id: 'rain_diagonal_tight',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 80,
      range: 0,
      arcDeg: 360,
      damage: 18,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 950,
        impactRadius: 0.78,
        offsets: [
          { x: 0, y: 0 },
          { x: -1.75, y: -1.75 },
          { x: 1.75, y: -1.75 },
          { x: -1.75, y: 1.75 },
          { x: 1.75, y: 1.75 },
        ],
      },
    },
    {
      id: 'rain_ring_tight',
      telegraphMs: 420,
      telegraphJitterMs: 0,
      activeMs: 80,
      recoveryMs: 80,
      range: 0,
      arcDeg: 360,
      damage: 18,
      lungeDistance: 0,
      parryable: false,
      kind: 'rain',
      rain: {
        impactDelayMs: 950,
        impactRadius: 0.78,
        offsets: [
          { x: 0, y: 2.15 },
          { x: 2.04, y: 0.66 },
          { x: 1.26, y: -1.74 },
          { x: -1.26, y: -1.74 },
          { x: -2.04, y: 0.66 },
        ],
      },
    },
  ],
  attackPattern: [0, 1, 2, 1, 3, 1],
  attackPatternPhaseTwo: [4, 1, 5, 1, 6, 1],
  attackCooldownMs: 140,
  attackCooldownJitterMs: 0,
  staggerMs: 1350,
};
