
import type { RegionName } from './layout';

export type UiLayer =
  | 'dom'
  | 'viewport'
  | 'world';

export type UiKind = 'control' | 'bar' | 'text' | 'panel' | 'shape';

export type UiProfile = 'game' | 'lab';

export interface UiElement {
  id: string;
  owner: string;
  layer: UiLayer;
  kind: UiKind;
  profiles: readonly UiProfile[];
  instanced?: boolean;
  reading?: boolean;
  region?: RegionName;
  migrated?: boolean;
  what: string;
}

export const UI_ELEMENTS = [
  {
    id: 'dom.panel',
    migrated: true,
    region: 'instruments',
    owner: 'index.html',
    layer: 'dom',
    kind: 'panel',
    profiles: ['lab'],
    what: 'instrument panel, 340px on the right edge',
  },
  {
    id: 'dom.panel.readout',
    migrated: true,
    region: 'instruments',
    owner: 'app/lab.ts',
    layer: 'dom',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'the panel’s monospace readout',
  },
  {
    id: 'dom.lab.action',
    migrated: true,
    region: 'instruments',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['lab'],
    instanced: true,
    what: 'one of the 41 lab command buttons',
  },
  {
    id: 'dom.coop.code',
    migrated: true,
    region: 'instruments',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['lab'],
    what: 'the room code being typed into, while entering somebody else’s session',
  },
  {
    id: 'dom.fps-meter',
    migrated: true,
    region: 'controls',
    owner: 'app/lab.ts',
    layer: 'dom',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'live FPS, latest frame time and one-second hitch summary',
  },
  {
    id: 'dom.toolbar',
    migrated: true,
    region: 'controls',
    owner: 'index.html',
    layer: 'dom',
    kind: 'panel',
    profiles: ['game', 'lab'],
    what: 'the top-right page-control strip',
  },
  {
    id: 'dom.toolbar.encounter',
    migrated: true,
    region: 'controls',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['lab'],
    what: 'encounter <select>',
  },
  {
    id: 'dom.toolbar.restart',
    migrated: true,
    region: 'controls',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['game', 'lab'],
    what: 'RESTART',
  },
  {
    id: 'dom.toolbar.pause',
    migrated: true,
    region: 'controls',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['game', 'lab'],
    what: 'PAUSE / RESUME',
  },
  {
    id: 'dom.toolbar.viewmode',
    migrated: true,
    region: 'controls',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['lab'],
    what: 'MODE: GAME / LAB',
  },
  {
    id: 'dom.toolbar.fullscreen',
    migrated: true,
    region: 'controls',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['game', 'lab'],
    what: 'FULLSCREEN / EXIT FULLSCREEN',
  },
  {
    id: 'dom.stick',
    migrated: true,
    region: 'thumbs',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['game', 'lab'],
    what: 'movement stick',
  },
  {
    id: 'dom.action',
    migrated: true,
    region: 'thumbs',
    owner: 'index.html',
    layer: 'dom',
    kind: 'control',
    profiles: ['game', 'lab'],
    instanced: true,
    what: 'one touch action button (the arc and the inboard three)',
  },

  {
    id: 'hud.health.bar',
    migrated: true,
    region: 'vitals',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'bar',
    profiles: ['game', 'lab'],
    what: 'player health, 260x10',
  },
  {
    id: 'hud.health.text',
    migrated: true,
    region: 'vitals',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'hp / maxHp beside the health bar',
  },
  {
    id: 'hud.stamina.bar',
    migrated: true,
    region: 'vitals',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'bar',
    profiles: ['game', 'lab'],
    what: 'player stamina, 260x6',
  },
  {
    id: 'hud.power.bar',
    migrated: true,
    region: 'vitals',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'bar',
    profiles: ['lab'],
    what: 'power readiness, 120x4 — the public profile suppresses it',
  },
  {
    id: 'hud.streak.text',
    migrated: true,
    region: 'vitals',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'parry streak counter',
  },
  {
    id: 'hud.riposte.text',
    migrated: true,
    region: 'affordance',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'RIPOSTE — a live affordance, shorter-lived than a glance',
  },
  {
    id: 'hud.peripheral.text',
    migrated: true,
    region: 'objective',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'attempt / wave / enemies / elapsed strip',
  },

  {
    id: 'hud.boss.name',
    migrated: true,
    region: 'threat',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'boss name, centred above its bar',
  },
  {
    id: 'hud.boss.bar',
    migrated: true,
    region: 'threat',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'bar',
    profiles: ['game', 'lab'],
    what: 'boss health, min(520, 48vw)',
  },
  {
    id: 'hud.boss.text',
    migrated: true,
    region: 'threat',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'boss hp / maxHp',
  },

  {
    id: 'hud.replay.text',
    migrated: true,
    region: 'objective',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'REPLAY banner',
  },
  {
    id: 'hud.tutorial.text',
    migrated: true,
    region: 'affordance',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['lab'],
    instanced: true,
    reading: true,
    what: 'the data-driven lesson line, wrapped',
  },
  {
    id: 'hud.outcome.text',
    migrated: true,
    region: 'verdict',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'VENCEU / TEMPO / MORTO',
  },
  {
    id: 'hud.retry.text',
    migrated: true,
    region: 'verdict',
    owner: 'render/hud.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'the device-appropriate restart hint',
  },

  {
    id: 'travel.prompt.text',
    migrated: true,
    region: 'affordance',
    owner: 'render/travel.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['lab'],
    instanced: true,
    reading: true,
    what: 'interaction prompt, wrapped',
  },

  {
    id: 'route.objective.text',
    migrated: true,
    region: 'objective',
    owner: 'render/route.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    instanced: true,
    reading: true,
    what: 'this node’s objective — clear the room, or take the door',
  },
  {
    id: 'route.prompt.text',
    migrated: true,
    region: 'affordance',
    owner: 'render/route.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    instanced: true,
    reading: true,
    what: 'route door prompt, wrapped',
  },
  {
    id: 'travel.dialogue.box',
    migrated: true,
    region: 'narration',
    owner: 'render/travel.ts',
    layer: 'viewport',
    kind: 'panel',
    profiles: ['lab'],
    what: 'dialogue frame, min(680, w-80) x 104',
  },
  {
    id: 'travel.dialogue.speaker',
    migrated: true,
    region: 'narration',
    owner: 'render/travel.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'speaker name inside the frame',
  },
  {
    id: 'travel.dialogue.text',
    migrated: true,
    region: 'narration',
    owner: 'render/travel.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'the spoken line — one unwrapped row',
  },
  {
    id: 'travel.dialogue.hint',
    migrated: true,
    region: 'narration',
    owner: 'render/travel.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'E  CONTINUE',
  },



  {
    id: 'herald.dialogue.box',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'panel',
    profiles: ['game', 'lab'],
    what: 'the herald’s offer panel, in the narration region',
  },
  {
    id: 'herald.dialogue.speaker',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'THE HERALD, and which of his offers is selected',
  },
  {
    id: 'herald.dialogue.text',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'text',
    instanced: true,
    profiles: ['game', 'lab'],
    reading: true,
    what: 'one ride he will give, marked when it is the one a press would take',
  },
  {
    id: 'herald.dialogue.hint',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'how to change the offer and how to take it, in this device’s vocabulary',
  },

  {
    id: 'envoy.dialogue.box',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'panel',
    profiles: ['game', 'lab'],
    what: 'the envoy’s panel, in the narration region',
  },
  {
    id: 'envoy.dialogue.speaker',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'THE ENVOY, and which of his lines is selected',
  },
  {
    id: 'envoy.dialogue.text',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'text',
    instanced: true,
    profiles: ['game', 'lab'],
    reading: true,
    what: 'calling a king, answering a call, or the room code once there is one',
  },
  {
    id: 'envoy.dialogue.aside',
    region: 'narration',
    owner: 'render/envoy.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'the room code being spelled, a dot per character still owed',
  },
  {
    id: 'envoy.dialogue.keys',
    region: 'narration',
    owner: 'render/envoy.ts',
    layer: 'viewport',
    kind: 'text',
    instanced: true,
    profiles: ['game', 'lab'],
    reading: true,
    what: 'the thirty-two-glyph alphabet plus DEL, SEND and BACK, steered with the stick',
  },
  {
    id: 'envoy.dialogue.hint',
    region: 'narration',
    owner: 'render/herald.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'how to choose and how to speak, in this device’s vocabulary',
  },

  {
    id: 'debug.timeline.panel',
    migrated: true,
    region: 'instruments',
    owner: 'render/debug.ts',
    layer: 'viewport',
    kind: 'panel',
    profiles: ['lab'],
    what: 'attack timeline backing plate, 580 wide',
  },
  {
    id: 'debug.mastery.panel',
    migrated: true,
    region: 'instruments',
    owner: 'render/debug.ts',
    layer: 'viewport',
    kind: 'panel',
    profiles: ['lab'],
    what: 'mastery estimate panel, top-left',
  },

  {
    id: 'world.npc.name',
    owner: 'render/travel.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['lab'],
    reading: true,
    what: 'NPC nameplate',
  },
  {
    id: 'victory.emblem',
    owner: 'render/victory.ts',
    layer: 'viewport',
    kind: 'shape',
    profiles: ['game'],
    what: 'faceted crown mark above the final route verdict',
  },
  {
    id: 'victory.feat.label',
    owner: 'render/victory.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game'],
    instanced: true,
    reading: true,
    what: 'the name of one thing the run earned, e.g. UNTOUCHED',
  },
  {
    id: 'victory.feat.note',
    owner: 'render/victory.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game'],
    instanced: true,
    reading: true,
    what: 'what that feat meant, in the player’s terms',
  },
  {
    id: 'victory.title',
    owner: 'render/victory.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'THE CROWN IS YOURS, once the last rung is cleared',
  },
  {
    id: 'victory.subtitle',
    owner: 'render/victory.ts',
    layer: 'viewport',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'what happened on this run — attempts, and whether the escort walked out',
  },
  {
    id: 'escort.name',
    owner: 'render/escort.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'Mara’s name, while she is still waiting in the court',
  },
  {
    id: 'escort.line',
    owner: 'render/escort.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'her offer to be escorted as far as the Blade',
  },
  {
    id: 'escort.prompt',
    owner: 'render/escort.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'the offer to take her along',
  },
  {
    id: 'envoy.name',
    owner: 'render/herald.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'the envoy’s role, shown when the king is close enough to hear him',
  },
  {
    id: 'envoy.standing',
    owner: 'render/herald.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'what he says while standing there — including that no road is open, in his own words',
  },
  {
    id: 'envoy.prompt',
    owner: 'render/herald.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'the invitation to speak to him; the lines themselves are in envoy.dialogue.*',
  },
  {
    id: 'herald.name',
    owner: 'render/herald.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'the herald’s role, shown when the king is close enough to hear him',
  },
  {
    id: 'herald.line',
    owner: 'render/herald.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'his one line, offering to take the king somewhere he has not earned',
  },
  {
    id: 'herald.prompt',
    owner: 'render/herald.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'the invitation to talk; the rides themselves are in herald.dialogue.*',
  },
  {
    id: 'armoury.stand.label',
    owner: 'render/armoury.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'the name on the plinth the king is standing at, in the opening court',
  },
  {
    id: 'armoury.stand.prompt',
    owner: 'render/armoury.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'the offer to switch to the power on the plinth the king is standing at',
  },
  {
    id: 'armoury.stand.note',
    owner: 'render/armoury.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'what that power does, or CARRIED when it is the one already held',
  },
  {
    id: 'pickup.power.prompt',
    owner: 'render/draw-projectiles.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game'],
    reading: true,
    what: 'the offer to take the power drop in the king’s reach — a power drop swaps mid-fight and waits for the action button rather than firing on contact',
  },
  {
    id: 'route.exit.label',
    owner: 'render/floor-pad.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'what is through the door out of this room — the next rung’s name on the route, the next seed on the generated chain. One element, two callers: `floor-pad.ts` draws both, and the route carries the worst case (`THE DOG-LEG PASSAGE` against `SALA 8`)',
  },
  {
    id: 'route.back.label',
    owner: 'render/floor-pad.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['game', 'lab'],
    reading: true,
    what: 'what is back through the door the king came in by — the previous rung, or the previous seed. Drawn dimmer than the way on, on a smaller ring, because it is a smaller offer — but at the same type size, which is the one channel a legibility floor forbids spending',
  },
  {
    id: 'world.enemy.health',
    owner: 'render/draw.ts',
    layer: 'world',
    kind: 'bar',
    profiles: ['game', 'lab'],
    instanced: true,
    what: 'per-enemy health, 34*zoom x 3',
  },
  {
    id: 'world.enemy.poise',
    owner: 'render/draw.ts',
    layer: 'world',
    kind: 'bar',
    profiles: ['game', 'lab'],
    instanced: true,
    what: 'per-enemy posture, drawn separately because a heavy answers it',
  },
  {
    id: 'world.player.health',
    owner: 'render/draw.ts',
    layer: 'world',
    kind: 'bar',
    profiles: ['game', 'lab'],
    instanced: true,
    what: 'a partner king’s health, over the body, the way an enemy’s is',
  },
  {
    id: 'world.companion.health',
    owner: 'render/draw.ts',
    layer: 'world',
    kind: 'bar',
    profiles: ['lab'],
    what: 'escort health, cleared of her face by a fixed screen gap',
  },
  {
    id: 'world.state.enemy',
    owner: 'render/debug.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['lab'],
    instanced: true,
    what: 'per-enemy state and elapsed ms',
  },
  {
    id: 'world.state.player',
    owner: 'render/debug.ts',
    layer: 'world',
    kind: 'text',
    profiles: ['lab'],
    what: 'player state and elapsed ms',
  },
] as const satisfies readonly UiElement[];

export type UiElementId = (typeof UI_ELEMENTS)[number]['id'];

export const UI_ELEMENT: ReadonlyMap<string, UiElement> = new Map(
  UI_ELEMENTS.map((element) => [element.id, element]),
);

export const uiElementsFor = (profile: UiProfile): readonly UiElement[] =>
  UI_ELEMENTS.filter((element) => (element.profiles as readonly UiProfile[]).includes(profile));
