
import { ASSEMBLY_HALL } from './assembly-hall';
import { CHANCELLERY } from './chancellery';
import { CORNER_KEEP } from './corner-keep';
import { FIRST_BLADE_ROOM } from './first-blade';
import { GUARD_HALL } from './guard-hall';
import { CROSSFIRE_COURT } from './crossfire-court';
import { DUEL_GALLERY } from './duel-gallery';
import { TRAINING_COURT } from './training-court';
import type { Ambience } from '../atmosphere';
import type { GenericArenaTheme, RoomRegistry, RoomTheme } from './theme';

const THEMES = {
  training_court: TRAINING_COURT,
  duel_gallery: DUEL_GALLERY,
  crossfire_court: CROSSFIRE_COURT,
  corner_keep: CORNER_KEEP,
  assembly_hall: ASSEMBLY_HALL,
  guard_hall: GUARD_HALL,
  chancellery: CHANCELLERY,
  first_blade: FIRST_BLADE_ROOM,
} as const;

const THEME_BY_ENCOUNTER: Readonly<Partial<Record<string, GenericArenaTheme>>> = {
  wayfarer_court: 'training_court',
  kernel_guard: 'training_court',
  kernel_duelist: 'duel_gallery',
  spacing_archer: 'crossfire_court',
  overlap_court: 'corner_keep',
  siege_10: 'assembly_hall',
  upper_hall: 'assembly_hall',
  captain: 'guard_hall',
  chancellor: 'chancellery',
  thorn_marshal: 'guard_hall',
  first_blade: 'first_blade',
};

const AMBIENCE: Record<string, Partial<Ambience>> = {
  wayfarer_court: {
    skyHigh: '#090811',
    skyHorizon: '#2c2133',
    skyLow: '#060609',
    key: '#e2ad58',
    fill: '#506f9a',
    dust: 66,
    fog: 0.44,
    windowSpacing: 3,
    windowStyle: 'court',
    parallaxStyle: 'inhabited',
    windowLight: 0.075,
    wallCondition: 'kept',
    glassStyle: 'amber',
    wallDisplay: 'heraldry',
  },
  kernel_guard: {
    skyHorizon: '#1e1523',
    key: '#d09a43',
    fill: '#334d6c',
    dust: 48,
    fog: 0.62,
    windowSpacing: 4.2,
    windowStyle: 'defensive',
    parallaxStyle: 'fortress',
    windowLight: 0.035,
    wallCondition: 'fortified',
    glassStyle: 'smoke',
    wallDisplay: 'arms',
  },
  kernel_duelist: {
    skyHigh: '#070812',
    skyHorizon: '#101427',
    skyLow: '#050609',
    key: '#a97c35',
    fill: '#314e73',
    dust: 34,
    fog: 0.74,
    windowSpacing: 5.6,
    windowStyle: 'lancet',
    parallaxStyle: 'high_court',
    windowLight: 0.05,
    wallCondition: 'weathered',
    glassStyle: 'frost',
    wallDisplay: 'heraldry',
  },
  spacing_archer: {
    skyHigh: '#080914',
    skyHorizon: '#17172d',
    skyLow: '#050509',
    key: '#b58b45',
    fill: '#4b5f8d',
    dust: 40,
    fog: 0.5,
    windowSpacing: 6.4,
    windowStyle: 'defensive',
    parallaxStyle: 'fortress',
    windowLight: 0.045,
    wallCondition: 'fortified',
    glassStyle: 'clear',
    wallDisplay: 'arms',
  },
  overlap_court: {
    skyHigh: '#090812',
    skyHorizon: '#241b2e',
    skyLow: '#06060a',
    key: '#d8a04a',
    fill: '#486b95',
    dust: 56,
    fog: 0.46,
    windowSpacing: 3.8,
    windowStyle: 'court',
    parallaxStyle: 'ruin',
    windowLight: 0.07,
    wallCondition: 'damaged',
    glassStyle: 'smoke',
    wallDisplay: 'service',
  },
  upper_hall: {
    skyHigh: '#070912',
    skyHorizon: '#101625',
    skyLow: '#040508',
    key: '#756c55',
    fill: '#334b68',
    dust: 24,
    fog: 0.82,
    windowSpacing: 5.8,
    windowStyle: 'lancet',
    parallaxStyle: 'high_court',
    windowLight: 0.1,
    wallCondition: 'weathered',
    glassStyle: 'frost',
    wallDisplay: 'records',
  },
  first_blade: {
    skyHigh: '#0b0710',
    skyHorizon: '#2a1829',
    skyLow: '#060408',
    key: '#dd9850',
    fill: '#515083',
    dust: 50,
    fog: 0.55,
    windowSpacing: 4.6,
    windowStyle: 'defensive',
    parallaxStyle: 'fortress',
    windowLight: 0,
    wallCondition: 'fortified',
    glassStyle: 'crimson',
    wallDisplay: 'arms',
  },
  captain: {
    skyHigh: '#0a0508',
    skyHorizon: '#25101a',
    skyLow: '#060305',
    key: '#e0783c',
    fill: '#5a2436',
    dust: 58,
    fog: 0.68,
  },
  siege_10: {
    skyHigh: '#0a0608',
    skyHorizon: '#2a151b',
    skyLow: '#060305',
    key: '#d4813d',
    fill: '#4c3a53',
    dust: 60,
    fog: 0.66,
    windowSpacing: 5,
    windowStyle: 'lancet',
    parallaxStyle: 'ruin',
    windowLight: 0.075,
    wallCondition: 'damaged',
    glassStyle: 'amber',
    wallDisplay: 'service',
  },
};

export const PUBLIC_ROOMS: RoomRegistry = {
  themeFor: (encounterId) => THEME_BY_ENCOUNTER[encounterId] ?? null,
  theme: (id) => THEMES[id as keyof typeof THEMES] as RoomTheme,
  ambience: (encounterId) => AMBIENCE[encounterId] ?? {},
};
