
import { ASSEMBLY_HALL } from './assembly-hall';
import { CHANCELLERY } from './chancellery';
import { CORNER_KEEP } from './corner-keep';
import { CROSSFIRE_COURT } from './crossfire-court';
import { DUEL_GALLERY } from './duel-gallery';
import { FIRST_BLADE_ROOM } from './first-blade';
import { GUARD_HALL } from './guard-hall';
import { TRAINING_COURT } from './training-court';
import { CONCEPT_BELL_COURT } from './concept-bell-court';
import { CONCEPT_PARALLAX_GALLERY } from './concept-parallax-gallery';
import { CONCEPT_PROP_GALLERY } from './concept-prop-gallery';
import { CONCEPT_KIT_GALLERY } from './concept-kit-gallery';
import { CONCEPT_CLUTTER_GALLERY } from './concept-clutter-gallery';
import { CONCEPT_RAIN_BREACHED_HALL } from './concept-rain-breached-hall';
import { CONCEPT_SHATTERED_DAIS } from './concept-shattered-dais';
import { CONCEPT_FALLEN_CROWN, CONCEPT_UNBOUND } from './concept-fidelity';
import type { Ambience } from '../atmosphere';
import type { GenericArenaTheme, RoomRegistry, RoomTheme } from './theme';

const THEMES: Record<GenericArenaTheme, RoomTheme> = {
  first_blade: FIRST_BLADE_ROOM,
  training_court: TRAINING_COURT,
  duel_gallery: DUEL_GALLERY,
  crossfire_court: CROSSFIRE_COURT,
  corner_keep: CORNER_KEEP,
  assembly_hall: ASSEMBLY_HALL,
  guard_hall: GUARD_HALL,
  chancellery: CHANCELLERY,
  concept_bell_court: CONCEPT_BELL_COURT,
  concept_shattered_dais: CONCEPT_SHATTERED_DAIS,
  concept_rain_breached_hall: CONCEPT_RAIN_BREACHED_HALL,
  concept_parallax_gallery: CONCEPT_PARALLAX_GALLERY,
  concept_prop_gallery: CONCEPT_PROP_GALLERY,
  concept_kit_gallery: CONCEPT_KIT_GALLERY,
  concept_clutter_gallery: CONCEPT_CLUTTER_GALLERY,
  concept_fallen_crown: CONCEPT_FALLEN_CROWN,
  concept_unbound: CONCEPT_UNBOUND,
};

const THEME_BY_ENCOUNTER: Readonly<Partial<Record<string, GenericArenaTheme>>> = {
  tutorial_fundamentals: 'training_court',
  tutorial_defense: 'training_court',
  tutorial_focus: 'training_court',
  tutorial_power: 'training_court',
  wayfarer_court: 'training_court',
  kernel_guard: 'training_court',
  generated_chambers: 'training_court',
  shape_combat_bowl: 'training_court',
  shape_cramped_keep: 'training_court',
  shape_gallery: 'duel_gallery',
  gallery_archer: 'crossfire_court',
  shape_twin_bowls: 'corner_keep',
  kernel_duelist: 'duel_gallery',
  background_encounter: 'duel_gallery',
  rotated_rectangle: 'crossfire_court',
  spacing_archer: 'crossfire_court',
  court_45s: 'crossfire_court',
  overlap_court: 'corner_keep',
  siege_10: 'assembly_hall',
  upper_hall: 'assembly_hall',
  captain: 'guard_hall',
  captain_read: 'guard_hall',
  chancellor: 'chancellery',
  thorn_marshal: 'guard_hall',
  first_blade: 'first_blade',
  concept_bell_court: 'concept_bell_court',
  concept_shattered_dais: 'concept_shattered_dais',
  concept_rain_breached_hall: 'concept_rain_breached_hall',
  concept_parallax_gallery: 'concept_parallax_gallery',
  concept_prop_gallery: 'concept_prop_gallery',
  concept_kit_gallery: 'concept_kit_gallery',
  concept_clutter_gallery: 'concept_clutter_gallery',
  concept_lantern_cloister: 'concept_fallen_crown',
  eternal_siege: 'concept_fallen_crown',
  concept_lantern_cloister_baked: 'concept_fallen_crown',
  concept_lantern_cloister_live: 'concept_fallen_crown',
  concept_oath_gallery: 'concept_fallen_crown',
  concept_guard_procession: 'concept_fallen_crown',
  concept_violet_chancellery: 'concept_fallen_crown',
  concept_rookery_roofs: 'concept_unbound',
  concept_chainbridge_court: 'concept_unbound',
  concept_flooded_nave: 'concept_unbound',
  concept_bell_foundry: 'concept_unbound',
  concept_archive_spiral: 'concept_unbound',
  concept_hollow_throne: 'concept_unbound',
};

const LANTERN_CLOISTER_AMBIENCE: Partial<Ambience> = {
  skyHigh: '#08070d', skyHorizon: '#251b2c', skyLow: '#050408',
  key: '#e2b466', fill: '#53688d', dust: 38, fog: 0.5,
  windowSpacing: 3.4, windowStyle: 'court', parallaxStyle: 'inhabited',
  windowLight: 0.09, wallCondition: 'kept', glassStyle: 'amber', wallDisplay: 'heraldry',
};

const AMBIENCE: Record<string, Partial<Ambience>> = {
  wayfarer_court: {
    skyHigh: '#090811',
    skyHorizon: '#2c2133',
    skyLow: '#060609',
    key: '#e2ad58',
    fill: '#506f9a',
    dust: 66,
    fog: 0.44,
    windowSpacing: 3,
    windowStyle: 'court',
    parallaxStyle: 'inhabited',
    windowLight: 0.075,
    wallCondition: 'kept',
    glassStyle: 'amber',
    wallDisplay: 'heraldry',
  },
  kernel_guard: {
    skyHorizon: '#1e1523',
    key: '#d09a43',
    fill: '#334d6c',
    dust: 48,
    fog: 0.62,
    windowSpacing: 4.2,
    windowStyle: 'defensive',
    parallaxStyle: 'fortress',
    windowLight: 0.035,
    wallCondition: 'fortified',
    glassStyle: 'smoke',
    wallDisplay: 'arms',
  },
  kernel_duelist: {
    skyHigh: '#070812',
    skyHorizon: '#101427',
    skyLow: '#050609',
    key: '#a97c35',
    fill: '#314e73',
    dust: 34,
    fog: 0.74,
    windowSpacing: 5.6,
    windowStyle: 'lancet',
    parallaxStyle: 'high_court',
    windowLight: 0.05,
    wallCondition: 'weathered',
    glassStyle: 'frost',
    wallDisplay: 'heraldry',
  },
  spacing_archer: {
    skyHigh: '#080914',
    skyHorizon: '#17172d',
    skyLow: '#050509',
    key: '#b58b45',
    fill: '#4b5f8d',
    dust: 40,
    fog: 0.5,
    windowSpacing: 6.4,
    windowStyle: 'defensive',
    parallaxStyle: 'fortress',
    windowLight: 0.045,
    wallCondition: 'fortified',
    glassStyle: 'clear',
    wallDisplay: 'arms',
  },
  overlap_court: {
    skyHigh: '#090812',
    skyHorizon: '#241b2e',
    skyLow: '#06060a',
    key: '#d8a04a',
    fill: '#486b95',
    dust: 56,
    fog: 0.46,
    windowSpacing: 3.8,
    windowStyle: 'court',
    parallaxStyle: 'ruin',
    windowLight: 0.07,
    wallCondition: 'damaged',
    glassStyle: 'smoke',
    wallDisplay: 'service',
  },
  upper_hall: {
    skyHigh: '#070912',
    skyHorizon: '#101625',
    skyLow: '#040508',
    key: '#756c55',
    fill: '#334b68',
    dust: 24,
    fog: 0.82,
    windowSpacing: 5.8,
    windowStyle: 'lancet',
    parallaxStyle: 'high_court',
    windowLight: 0.1,
    wallCondition: 'weathered',
    glassStyle: 'frost',
    wallDisplay: 'records',
  },
  first_blade: {
    skyHigh: '#0b0710',
    skyHorizon: '#2a1829',
    skyLow: '#060408',
    key: '#dd9850',
    fill: '#515083',
    dust: 50,
    fog: 0.55,
    windowSpacing: 4.6,
    windowStyle: 'defensive',
    parallaxStyle: 'fortress',
    windowLight: 0,
    wallCondition: 'fortified',
    glassStyle: 'crimson',
    wallDisplay: 'arms',
  },
  siege_10: {
    skyHigh: '#0a0608',
    skyHorizon: '#2a151b',
    skyLow: '#060305',
    key: '#d4813d',
    fill: '#4c3a53',
    dust: 60,
    fog: 0.66,
    windowSpacing: 5,
    windowStyle: 'lancet',
    parallaxStyle: 'ruin',
    windowLight: 0.075,
    wallCondition: 'damaged',
    glassStyle: 'amber',
    wallDisplay: 'service',
  },
  captain: { skyHigh: '#0a0508', skyHorizon: '#25101a', skyLow: '#060305', key: '#e0783c', fill: '#5a2436', dust: 58, fog: 0.68 },
  captain_read: { skyHigh: '#0a0508', skyHorizon: '#25101a', skyLow: '#060305', key: '#e0783c', fill: '#5a2436', dust: 58, fog: 0.68 },
  maze_serpentine: { windowSpacing: 8.5 },
  concept_bell_court: {
    skyHigh: '#08060d',
    skyHorizon: '#2c1823',
    skyLow: '#050306',
    key: '#e0a34b',
    fill: '#465a78',
    dust: 64,
    fog: 0.56,
    windowSpacing: 4.4,
    windowStyle: 'court',
    parallaxStyle: 'fortress',
    windowLight: 0.055,
    wallCondition: 'weathered',
    glassStyle: 'amber',
    wallDisplay: 'heraldry',
  },
  concept_shattered_dais: {
    skyHigh: '#08070d',
    skyHorizon: '#211622',
    skyLow: '#050407',
    key: '#bc8241',
    fill: '#4a506d',
    dust: 72,
    fog: 0.64,
    windowSpacing: 5.4,
    windowStyle: 'defensive',
    parallaxStyle: 'ruin',
    windowLight: 0.035,
    wallCondition: 'damaged',
    glassStyle: 'smoke',
    wallDisplay: 'arms',
  },
  concept_rain_breached_hall: {
    skyHigh: '#050912',
    skyHorizon: '#13263b',
    skyLow: '#03070d',
    key: '#7893a8',
    fill: '#4f7897',
    dust: 28,
    fog: 0.78,
    windowSpacing: 4.8,
    windowStyle: 'lancet',
    parallaxStyle: 'ruin',
    windowLight: 0.14,
    wallCondition: 'damaged',
    glassStyle: 'frost',
    wallDisplay: 'service',
  },
  concept_parallax_gallery: {
    skyHigh: '#090817',
    skyHorizon: '#302644',
    skyLow: '#070610',
    key: '#d8ad62',
    fill: '#5875a5',
    dust: 42,
    fog: 0.38,
    windowSpacing: 3.2,
    windowStyle: 'court',
    parallaxStyle: 'inhabited',
    windowLight: 0.11,
    wallCondition: 'kept',
    glassStyle: 'clear',
    wallDisplay: 'heraldry',
  },
  concept_prop_gallery: {
    skyHigh: '#08070e',
    skyHorizon: '#251d31',
    skyLow: '#050409',
    key: '#d6a14f',
    fill: '#4e6288',
    dust: 36,
    fog: 0.52,
    windowSpacing: 4,
    windowStyle: 'court',
    parallaxStyle: 'high_court',
    windowLight: 0.065,
    wallCondition: 'kept',
    glassStyle: 'amber',
    wallDisplay: 'records',
  },
  concept_kit_gallery: {
    skyHigh: '#070710',
    skyHorizon: '#211d2c',
    skyLow: '#040409',
    key: '#d2aa63',
    fill: '#536786',
    dust: 30,
    fog: 0.44,
    windowSpacing: 0,
    windowStyle: 'lancet',
    parallaxStyle: 'fortress',
    windowLight: 0,
    wallCondition: 'kept',
    glassStyle: 'clear',
    wallDisplay: 'none',
  },
  concept_clutter_gallery: {
    skyHigh: '#07060d',
    skyHorizon: '#241b26',
    skyLow: '#040308',
    key: '#d0a05b',
    fill: '#56647e',
    dust: 32,
    fog: 0.48,
    windowSpacing: 0,
    windowStyle: 'lancet',
    parallaxStyle: 'inhabited',
    windowLight: 0,
    wallCondition: 'weathered',
    glassStyle: 'smoke',
    wallDisplay: 'none',
  },
  concept_lantern_cloister: LANTERN_CLOISTER_AMBIENCE,
  eternal_siege: LANTERN_CLOISTER_AMBIENCE,
  concept_lantern_cloister_baked: LANTERN_CLOISTER_AMBIENCE,
  concept_lantern_cloister_live: LANTERN_CLOISTER_AMBIENCE,
  concept_oath_gallery: {
    skyHigh: '#08070d', skyHorizon: '#21172a', skyLow: '#050408',
    key: '#d7a64f', fill: '#4b5c83', dust: 34, fog: 0.58,
    windowSpacing: 5.2, windowStyle: 'defensive', parallaxStyle: 'fortress',
    windowLight: 0.045, wallCondition: 'kept', glassStyle: 'smoke', wallDisplay: 'heraldry',
  },
  concept_guard_procession: {
    skyHigh: '#09060a', skyHorizon: '#29151d', skyLow: '#050305',
    key: '#d99445', fill: '#4d465d', dust: 44, fog: 0.62,
    windowSpacing: 6, windowStyle: 'defensive', parallaxStyle: 'fortress',
    windowLight: 0.035, wallCondition: 'fortified', glassStyle: 'crimson', wallDisplay: 'arms',
  },
  concept_violet_chancellery: {
    skyHigh: '#090712', skyHorizon: '#281b39', skyLow: '#050408',
    key: '#b87bd4', fill: '#565083', dust: 40, fog: 0.56,
    windowSpacing: 4.2, windowStyle: 'court', parallaxStyle: 'high_court',
    windowLight: 0.075, wallCondition: 'kept', glassStyle: 'frost', wallDisplay: 'records',
  },
  concept_rookery_roofs: {
    skyHigh: '#090b18', skyHorizon: '#3b304f', skyLow: '#070711',
    key: '#a7906a', fill: '#66799d', dust: 30, fog: 0.35,
    windowSpacing: 7, windowStyle: 'defensive', parallaxStyle: 'inhabited',
    windowLight: 0.035, wallCondition: 'weathered', glassStyle: 'smoke', wallDisplay: 'arms',
  },
  concept_chainbridge_court: {
    skyHigh: '#070711', skyHorizon: '#2b2037', skyLow: '#040408',
    key: '#ca9248', fill: '#4d5d7e', dust: 42, fog: 0.48,
    windowSpacing: 7, windowStyle: 'defensive', parallaxStyle: 'fortress',
    windowLight: 0.035, wallCondition: 'fortified', glassStyle: 'smoke', wallDisplay: 'heraldry',
  },
  concept_flooded_nave: {
    skyHigh: '#060914', skyHorizon: '#1e2b46', skyLow: '#03060c',
    key: '#8da4b6', fill: '#527b9c', dust: 22, fog: 0.74,
    windowSpacing: 3.8, windowStyle: 'lancet', parallaxStyle: 'ruin',
    windowLight: 0.13, wallCondition: 'damaged', glassStyle: 'frost', wallDisplay: 'service',
  },
  concept_bell_foundry: {
    skyHigh: '#0b0606', skyHorizon: '#351612', skyLow: '#060302',
    key: '#f08b35', fill: '#5f3c36', dust: 76, fog: 0.66,
    windowSpacing: 6.5, windowStyle: 'defensive', parallaxStyle: 'ruin',
    windowLight: 0.025, wallCondition: 'damaged', glassStyle: 'smoke', wallDisplay: 'service',
  },
  concept_archive_spiral: {
    skyHigh: '#07060b', skyHorizon: '#241829', skyLow: '#040306',
    key: '#b98243', fill: '#4a4764', dust: 62, fog: 0.7,
    windowSpacing: 7, windowStyle: 'lancet', parallaxStyle: 'high_court',
    windowLight: 0.025, wallCondition: 'weathered', glassStyle: 'smoke', wallDisplay: 'records',
  },
  concept_hollow_throne: {
    skyHigh: '#090711', skyHorizon: '#392543', skyLow: '#050408',
    key: '#c48b4a', fill: '#5b5578', dust: 54, fog: 0.42,
    windowSpacing: 8, windowStyle: 'court', parallaxStyle: 'ruin',
    windowLight: 0.035, wallCondition: 'damaged', glassStyle: 'crimson', wallDisplay: 'heraldry',
  },
};

export const LAB_ROOMS: RoomRegistry = {
  themeFor: (encounterId) => THEME_BY_ENCOUNTER[encounterId] ?? null,
  theme: (id) => THEMES[id],
  ambience: (encounterId) => AMBIENCE[encounterId] ?? {},
};

export const LAB_ROOM_DECLARATIONS = {
  themed: Object.keys(THEME_BY_ENCOUNTER),
  lit: Object.keys(AMBIENCE),
} as const;
