
import type { ModelDef } from '../models';


export const FIRST_BLADE_CROWNED: ModelDef = /* @__PURE__ */ (() => ({
  id: 'first_blade_crowned',
  heightPx: 62,
  widthScale: 1.42,
  flatArticulation: {
    weapon: { pivot: [-1.08, 0.5], rotationScale: 0.6 },
  },
  viewWidthScale: { profile: 0.76 },
  viewPartOrder: {
    front: ['legTrail', 'legLead', 'body', 'head', 'weapon'],
    back: ['weapon', 'legTrail', 'legLead', 'body', 'head'],
    profile: ['legTrail', 'legLead', 'body', 'head', 'weapon'],
  },
  shapes: [
    {
      kind: 'poly',
      points: [
        [-0.84, 0.08],
        [-0.68, 0.58],
        [-0.42, 0.86],
        [0.34, 0.78],
        [0.7, 0.48],
        [0.56, 0.04],
        [0.12, 0.16],
        [-0.06, 0.02],
      ],
      fill: 'tint',
      stroke: 'outline',
      width: 2,
    },
    {
      part: 'legTrail',
      kind: 'poly',
      points: [
        [-0.48, 0],
        [-0.38, 0.3],
        [-0.12, 0.3],
        [-0.18, 0],
      ],
      fill: 'garment',
      stroke: 'outline',
      width: 1.2,
      shade: 0.72,
    },
    {
      part: 'legLead',
      kind: 'poly',
      points: [
        [0.12, 0],
        [0.08, 0.3],
        [0.38, 0.3],
        [0.48, 0],
      ],
      fill: 'garment',
      stroke: 'outline',
      width: 1.2,
      shade: 0.62,
    },
    {
      kind: 'poly',
      points: [
        [-0.5, 0.66],
        [-0.18, 1.0],
        [0.08, 0.82],
        [0.48, 0.94],
        [0.34, 0.62],
      ],
      fill: 'garment',
      stroke: 'outline',
      width: 2,
    },
    {
      part: 'head',
      kind: 'poly',
      points: [
        [-0.22, 0.82],
        [-0.16, 1.08],
        [0.18, 1.08],
        [0.24, 0.82],
        [0.02, 0.72],
      ],
      fill: 'tint',
      stroke: 'outline',
      width: 2,
    },
    {
      part: 'head',
      kind: 'poly',
      points: [
        [-0.2, 1.06],
        [-0.28, 1.28],
        [-0.06, 1.16],
        [0.02, 1.34],
        [0.12, 1.16],
        [0.3, 1.26],
        [0.2, 1.04],
      ],
      fill: 'firstBlade',
      stroke: 'outline',
      width: 1.5,
    },
    {
      kind: 'line',
      points: [
        [-0.48, 0.68],
        [0.36, 0.18],
      ],
      stroke: 'firstBlade',
      width: 3,
    },
    {
      part: 'weapon',
      kind: 'line',
      points: [
        [-1.22, 0.48],
        [1.18, 0.92],
      ],
      stroke: 'hudText',
      width: 3,
    },
    {
      part: 'weapon',
      kind: 'poly',
      points: [
        [-1.34, 0.43],
        [-1.05, 0.43],
        [-1.16, 0.62],
      ],
      fill: 'firstBlade',
      stroke: 'outline',
      width: 1.5,
    },
    {
      part: 'weapon',
      kind: 'poly',
      points: [
        [1.02, 0.8],
        [1.5, 0.82],
        [1.68, 0.96],
        [1.52, 1.13],
        [1.14, 1.22],
        [0.88, 1.05],
        [1.2, 1.04],
        [1.4, 0.96],
        [1.18, 0.88],
      ],
      fill: 'hudText',
      stroke: 'outline',
      width: 1.5,
    },
    {
      part: 'weapon',
      kind: 'ellipse',
      cx: -0.58,
      cy: 0.6,
      rx: 0.09,
      ry: 0.055,
      fill: 'garment',
      stroke: 'outline',
      width: 1,
    },
    {
      part: 'weapon',
      kind: 'ellipse',
      cx: -0.16,
      cy: 0.68,
      rx: 0.09,
      ry: 0.055,
      fill: 'garment',
      stroke: 'outline',
      width: 1,
    },
  ],
}))();
